# Generated by Django 3.2 on 2021-08-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210726_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='locaistrabalhados',
            name='categoria',
            field=models.CharField(choices=[('hospitais', 'Hospital'), ('viadutos', 'Viaduto'), ('casa_repusos', 'Casa De Repouso')], default='hospitais', max_length=200),
        ),
        migrations.AlterField(
            model_name='locaistrabalhados',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locaistrabalhados',
            name='local',
            field=models.CharField(max_length=100),
        ),
    ]
