# Generated by Django 3.2.2 on 2021-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210803_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locaistrabalhados',
            name='categoria',
            field=models.CharField(choices=[('hospitais', 'Hospital'), ('viadutos', 'Viaduto'), ('casa_repousos', 'Casa De Repouso')], default='hospitais', max_length=200),
        ),
    ]
